#!/bin/sh
xrdb ~/.Xresources
setxkbmap -option caps:escape
dunst &
#dunst -c ~/.config/dunst/dunstrc &
/usr/bin/xautolock -time 45 -detectsleep -locker "systemctl suspend" &
urxvtd -q -f -o && sleep 1 && urxvtc -name dropTerm &

environment=$1
if [[ -n "$environment" ]]; then
    # echo $environment
    case "$environment" in
        sway)
            export SDL_VIDEODRIVER=wayland
            export GDK_BACKEND=wayland
            export CLUTTER_BACKEND=wayland
            ;;
        i3)
            ;;
        *)
            echo $"Usage: $0 {sway|i3}"
            exit 1

    esac
fi
